"""Defines the repository rule backing the autodetected host platform at //host."""

load("//os/linux/libc/glibc:glibc.bzl", "glibc_version_constraints")
load("//os/linux/libc/glibc:glibc_private.bzl", "GLIBC_VERSIONS")
load("//os/linux/libc/musl:musl.bzl", "musl_version_constraints")
load("//os/linux/libc/musl:musl_private.bzl", "MUSL_VERSIONS")
load(":feature_mapping.bzl", "x86_64_feature_constraint_names")
load(":prebuilts.bzl", "PREBUILT_DETECTORS")

visibility(["//..."])

# The valid values of the PLATFORMS_CONTRIB_HOST_DETECTION environment variable, which controls
# CPU feature detection:
#
#   * auto (default): detect CPU features with a prebuilt detector binary if one is available for
#     the host, otherwise emit a warning and don't declare any CPU feature constraint values.
#   * off: skip CPU feature detection entirely (and silence all related warnings).
_DETECTION_MODES = ["auto", "off"]

_BUILD_TEMPLATE = """\
# Generated by the host_platform_repository repository rule from
# @platforms_contrib//host/private:host_platform.bzl. Do not modify: changes will be lost when the
# repository is refetched. Regenerate with `bazel sync --configure` after a hardware or OS change.

platform(
    name = "host",
    constraint_values = [
{constraint_values}    ],
    parents = ["{parent}"],
    visibility = ["//visibility:public"],
)
"""

def _normalize_os(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    if os_name.startswith("linux"):
        return "linux"
    if os_name.startswith("mac"):
        return "macos"
    if os_name.startswith("windows"):
        return "windows"
    return "other"

def _normalize_arch(repository_ctx):
    arch = repository_ctx.os.arch.lower()
    if arch in ["amd64", "x86_64", "x64"]:
        return "amd64"
    if arch in ["aarch64", "arm64"]:
        return "arm64"
    return "other"

def _version_key(version):
    """Parses a dotted version string into a list of ints for comparison, or None if invalid."""
    parts = version.split(".")
    for part in parts:
        if not part.isdigit():
            return None
    return [int(part) for part in parts]

def _clamp_version(detected, known_versions):
    """Returns the highest version in known_versions that is <= detected, or None."""
    detected_key = _version_key(detected)
    if not detected_key:
        return None
    best = None
    for version in known_versions:
        key = _version_key(version)
        if key <= detected_key and (best == None or key > _version_key(best)):
            best = version
    return best

def _detect_glibc_version(repository_ctx):
    getconf = repository_ctx.which("getconf")
    if getconf:
        result = repository_ctx.execute([getconf, "GNU_LIBC_VERSION"])

        # Prints e.g. "glibc 2.39".
        if result.return_code == 0 and result.stdout.strip().startswith("glibc "):
            return _clamp_version(result.stdout.strip().split(" ")[-1], GLIBC_VERSIONS)

    ldd = repository_ctx.which("ldd")
    if ldd:
        result = repository_ctx.execute([ldd, "--version"])

        # glibc's ldd prints e.g. "ldd (Ubuntu GLIBC 2.39-0ubuntu8.4) 2.39" as the first line.
        first_line = result.stdout.splitlines()[0] if result.stdout else ""
        if result.return_code == 0 and ("glibc" in first_line.lower() or "gnu libc" in first_line.lower()):
            return _clamp_version(first_line.split(" ")[-1], GLIBC_VERSIONS)

    return None

def _detect_musl_version(repository_ctx):
    lib_dir = repository_ctx.path("/lib")
    if not lib_dir.exists:
        return None
    for entry in lib_dir.readdir():
        if entry.basename.startswith("ld-musl-") and entry.basename.endswith(".so.1"):
            # The musl loader prints its usage message, which includes a "Version 1.2.5" line, to
            # stderr and exits with a non-zero code when invoked without arguments.
            result = repository_ctx.execute([entry])
            for line in result.stderr.splitlines():
                if line.strip().startswith("Version "):
                    return _clamp_version(line.strip().split(" ")[-1], MUSL_VERSIONS)
    return None

def _libc_constraints(repository_ctx):
    glibc_version = _detect_glibc_version(repository_ctx)
    if glibc_version:
        return [str(label) for label in glibc_version_constraints(glibc_version)]
    musl_version = _detect_musl_version(repository_ctx)
    if musl_version:
        return [str(label) for label in musl_version_constraints(musl_version)]
    return []

def _download_prebuilt_detector(repository_ctx, os, arch, output):
    prebuilt = PREBUILT_DETECTORS.get((os, arch))
    if not prebuilt:
        return None
    result = repository_ctx.download(
        url = prebuilt.url,
        output = output,
        integrity = prebuilt.integrity,
        executable = True,
        allow_fail = True,
    )
    if not result.success:
        return None
    return repository_ctx.path(output)

def _warn(message):
    # buildifier: disable=print
    print("""\
@platforms_contrib//host: {message}. The host platform will not declare any CPU feature \
constraint values. Set PLATFORMS_CONTRIB_HOST_DETECTION=off to silence this warning.""".format(
        message = message,
    ))

def _detect_x86_64_features(repository_ctx, os, arch):
    """Returns the list of constraint value names in //cpu/x86_64/feature matching the host CPU."""
    output = "detect_cpu.exe" if os == "windows" else "detect_cpu"

    detector = _download_prebuilt_detector(repository_ctx, os, arch, output)
    if not detector:
        _warn("no prebuilt CPU feature detector could be downloaded for this host (os: {os}, cpu: {arch})".format(
            os = os,
            arch = arch,
        ))
        return []

    result = repository_ctx.execute([detector])
    if result.return_code != 0:
        _warn("the CPU feature detector failed to run: " + result.stderr.strip())
        return []

    reported_arch = None
    reported_features = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.startswith("arch:"):
            reported_arch = line[len("arch:"):]
        elif line.startswith("feature:"):
            reported_features.append(line[len("feature:"):])

    if reported_arch != "x86_64":
        # E.g. an x86-64 Bazel running under emulation on a different host architecture. Adding
        # x86-64 feature constraint values could clash with the parent platform's CPU constraint.
        _warn("the CPU feature detector reported architecture '{arch}' instead of x86_64".format(
            arch = reported_arch,
        ))
        return []

    return x86_64_feature_constraint_names(reported_features)

def _host_platform_repository_impl(repository_ctx):
    os = _normalize_os(repository_ctx)
    arch = _normalize_arch(repository_ctx)

    mode = repository_ctx.getenv("PLATFORMS_CONTRIB_HOST_DETECTION") or "auto"
    if mode not in _DETECTION_MODES:
        fail("PLATFORMS_CONTRIB_HOST_DETECTION must be one of [{modes}], got: {mode}".format(
            modes = ", ".join(_DETECTION_MODES),
            mode = mode,
        ))

    constraints = []
    if os == "linux":
        constraints += _libc_constraints(repository_ctx)
    if arch == "amd64" and mode != "off":
        constraints += [
            str(Label("//cpu/x86_64/feature:" + name))
            for name in _detect_x86_64_features(repository_ctx, os, arch)
        ]

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        constraint_values = "".join([
            "        \"{}\",\n".format(constraint)
            for constraint in constraints
        ]),
        parent = str(Label("@platforms//host")),
    ))

host_platform_repository = repository_rule(
    implementation = _host_platform_repository_impl,
    configure = True,
    doc = """\
Generates a `platform` target named `host` that extends `@platforms//host` with the constraint
values from platforms_contrib that match the host machine: the available glibc/musl version on
Linux and the available x86-64 CPU features (and thus microarchitecture levels).

CPU features are detected by running a prebuilt binary built on the cpu_features library (see
//prebuilt); if none is available for the host, the platform doesn't declare any CPU feature
constraint values. Set the PLATFORMS_CONTRIB_HOST_DETECTION environment variable to `off` to skip
CPU feature detection entirely.""",
)
