"""Repository rule that detects the host's libc and libc version.

The rule generates `host.bzl` exposing `HOST_CONSTRAINT_VALUES`, a list of
Label objects that platform definitions can splice into their
`constraint_values` attribute. On non-Linux hosts the list is empty: every
other relevant constraint is already known at compile time.

On Linux it tries the prebuilt detector pinned in
`private/detector/versions.bzl`. If no pin exists for the current host or
the SHA is still a placeholder (typical for HEAD between releases), it
falls back to compiling the detector from source using `$CC`, `clang`,
`gcc`, or `cc` from the user's PATH.

The detector emits one repo-relative label per line. The rule prefixes
each with `@platforms_contrib` and wraps it in a `Label()` call in the
generated `host.bzl`.
"""

load("//private/detector:versions.bzl", "BINARIES", "VERSION")

visibility("//...")

_DOWNLOAD_URL_TEMPLATE = (
    "https://github.com/bazel-contrib/platforms_contrib/releases/download/" +
    "{version}/{asset}"
)

_PLACEHOLDER_SHA_PREFIX = "000000"

_DETECTOR_SOURCE = Label("//private/detector:src/detector.c")

# Compilers to try (in order) when compiling from source. `$CC` from the env
# wins when set.
_COMPILER_CANDIDATES = ["clang", "gcc", "cc"]

def _linux_host_key(repository_ctx):
    """Returns the Linux host key ("linux_<cpu>") or None for non-Linux hosts."""
    os_name = repository_ctx.os.name.lower()
    if not os_name.startswith("linux"):
        return None

    arch = repository_ctx.os.arch.lower()
    if arch in ("x86_64", "amd64", "x64"):
        return "linux_x86_64"
    if arch in ("aarch64", "arm64"):
        return "linux_aarch64"
    fail("Unsupported Linux host CPU for platforms_contrib host detection: " + arch)

def _parse_labels(stdout):
    labels = []
    for raw in stdout.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if not line.startswith("//"):
            fail("platforms_contrib detector emitted non-repo-relative label: " + line)
        labels.append(line)
    return labels

def _download_prebuilt(repository_ctx, host_key):
    info = BINARIES.get(host_key)
    if info == None:
        return None
    if info["sha256"].startswith(_PLACEHOLDER_SHA_PREFIX):
        return None

    binary_name = "detector"
    repository_ctx.download(
        url = _DOWNLOAD_URL_TEMPLATE.format(version = VERSION, asset = info["asset"]),
        sha256 = info["sha256"],
        output = binary_name,
        executable = True,
    )
    return binary_name

def _compile_from_source(repository_ctx):
    source = repository_ctx.path(_DETECTOR_SOURCE)
    output_name = "detector"

    cc_env = repository_ctx.os.environ.get("CC", "").strip()
    candidates = []
    if cc_env:
        candidates.append(cc_env)
    candidates.extend(_COMPILER_CANDIDATES)

    tried = []
    last_error = ""
    for compiler in candidates:
        path = repository_ctx.which(compiler)
        if path == None:
            continue
        tried.append(str(path))
        result = repository_ctx.execute(
            [str(path), "-std=c11", "-Os", "-o", output_name, str(source)],
            timeout = 120,
        )
        if result.return_code == 0:
            return output_name
        last_error = "{}: exit {}\n{}\n{}".format(
            str(path),
            result.return_code,
            result.stdout,
            result.stderr,
        )

    if not tried:
        fail(
            "platforms_contrib host detection needs a C compiler in PATH (set $CC or install " +
            "one of {}); none found.".format(_COMPILER_CANDIDATES),
        )
    fail("platforms_contrib host detector failed to compile from source.\nLast error:\n" + last_error)

def _write_outputs(repository_ctx, source, raw_labels):
    label_calls = [
        "Label(\"@platforms_contrib{}\")".format(label)
        for label in raw_labels
    ]
    rendered_list = "[\n" + "".join(["    " + call + ",\n" for call in label_calls]) + "]"
    raw_block = "".join(["#   " + l + "\n" for l in raw_labels]) or "#   (none)\n"

    repository_ctx.file(
        "BUILD.bazel",
        "# Generated by @platforms_contrib//private:host_detect.bzl.\n" +
        "exports_files([\"host.bzl\"])\n",
    )
    repository_ctx.file(
        "host.bzl",
        "# Generated by @platforms_contrib//private:host_detect.bzl.\n" +
        "# Source: " + source + "\n" +
        "# Detected labels:\n" +
        raw_block +
        "\n" +
        "HOST_CONSTRAINT_VALUES = " + rendered_list + "\n",
    )

def _host_detect_impl(repository_ctx):
    host_key = _linux_host_key(repository_ctx)
    if host_key == None:
        _write_outputs(repository_ctx, "non-linux", [])
        return

    binary_name = _download_prebuilt(repository_ctx, host_key)
    source = "prebuilt"
    if binary_name == None:
        binary_name = _compile_from_source(repository_ctx)
        source = "compiled"

    result = repository_ctx.execute(
        [repository_ctx.path(binary_name)],
        timeout = 30,
    )
    if result.return_code != 0:
        fail("platforms_contrib host detector exited with code {}\nstdout:\n{}\nstderr:\n{}".format(
            result.return_code,
            result.stdout,
            result.stderr,
        ))

    _write_outputs(repository_ctx, source, _parse_labels(result.stdout))

host_detect = repository_rule(
    implementation = _host_detect_impl,
    configure = True,
    environ = ["CC", "PATH"],
    doc = "Detects host libc properties by running a (downloaded or freshly compiled) detector binary.",
)
